In [ ]:
import pandas as pd

npr = pd.read_excel('/content/custom.xlsx')
npr.head()


Date                                             Ärende  \
0  2022-07-05 11:02:27  hallå hallå  ja det är lite dålig täckning äve...   
1  2022-07-05 11:02:27  hallå hallå  ja det är lite dålig täckning äve...   
2  2022-07-05 11:02:27  hallå hallå  ja det är lite dålig täckning äve...   
3  2022-07-05 11:02:27  hallå hallå  ja det är lite dålig täckning äve...   
4  2022-07-05 11:02:27  hallå hallå  ja det är lite dålig täckning äve...   

                                             phrases  \
0  början ren väldigt torr, klippen  smörkniv väl...   
1  början ren väldigt torr, klippen  smörkniv väl...   
2  början ren väldigt torr, klippen  smörkniv väl...   
3  början ren väldigt torr, klippen  smörkniv väl...   
4  början ren väldigt torr, klippen  smörkniv väl...   

                                         phrase  
0                       början ren väldigt torr  
1   klippen  smörkniv väldigt leverpastej tryck  
2                               ryska kattlådan  
3                             ställen kattlådan  
4                           kattlådan sovrummet

In [ ]:
import pandas as pd
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
nltk.download('stopwords')
nltk.download('punkt')

# Read the Excel file into a pandas dataframe
df = pd.read_excel('f.xlsx')

# Set the Swedish stop words
swedish_stopwords = set(stopwords.words('swedish'))

# Loop through each row of the dataframe
for i, row in df.iterrows():
    # Get the text from the current row
    text = row['Ärende']

    # Tokenize the text into individual words
    words = word_tokenize(text.lower())

    # Remove the stop words
    filtered_words = [word for word in words if word.casefold() not in swedish_stop_words]

    # Join the remaining words back into a string
    filtered_text = " ".join(filtered_words)

    # Update the 'Text' column in the current row with the filtered text
    df.at[i, 'Ärende'] = filtered_text

# Write the updated dataframe to a new Excel file
df.to_excel('example_filtered.xlsx', index=False)



[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


In [ ]:
import pandas as pd
import numpy as np
import nltk
from nltk.corpus import stopwords
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.decomposition import NMF
nltk.download('stopwords')
nltk.download('punkt')

# Read the Excel file into a pandas dataframe
df = pd.read_excel('custom.xlsx')#sheet_name='Sheet1')

# Set the Swedish stop words
swedish_stop_words = set(stopwords.words('swedish'))

# Tokenize the text and remove stop words
text_data = []
for i, row in df.iterrows():
    text = row['phrases']
    words = nltk.word_tokenize(text.lower())
    filtered_words = [word for word in words if word.casefold() not in swedish_stop_words]
    text_data.append(" ".join(filtered_words))

# Convert the text data into a matrix of TF-IDF features
#vectorizer = TfidfVectorizer(max_df=0.95, min_df=
tfidf = TfidfVectorizer(max_df=0.95, min_df=2)



[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


In [ ]:
# Fit and transform text data
dtm = tfidf.fit_transform(npr['phrases'])

In [ ]:
from sklearn.decomposition import NMF
nmf_model = NMF(n_components=10,random_state=42)
nmf_model.fit(dtm)

NMF(n_components=10, random_state=42)

In [ ]:
len(tfidf.get_feature_names_out())

6421

In [ ]:
import random
for i in range(10):
    random_word_id = random.randint(0,4280)
    print(tfidf.get_feature_names_out()[random_word_id])

julens
artist
adam
ledaren
albin
majsvälling
klippningen
kristersson
kanonkväll
birds


In [ ]:

len(nmf_model.components_)

10

In [ ]:

nmf_model.components_

len(nmf_model.components_[0])

6421

In [ ]:
single_topic = nmf_model.components_[0]

single_topic.argsort()

array([3210, 1314, 5718, ..., 6203, 6023,  965])

In [ ]:
len(single_topic)

6421

In [ ]:
single_topic[4000]

0.010171050267866978

In [ ]:
single_topic[4238]

0.0013047666144405717

In [ ]:
single_topic.argsort()[-10:]

array([1905, 5542,  217, 1196, 2019, 5541, 2024, 6203, 6023,  965])

In [ ]:
top_word_indices = single_topic.argsort()[-10:]

for index in top_word_indices:
    print(tfidf.get_feature_names_out()[index])

hela
tiden
appen
fall
hund
tid
hunden
vårdguiden
veterinär
djurens


In [ ]:
for index,topic in enumerate(nmf_model.components_):
    print(f'THE TOP 15 WORDS FOR TOPIC #{index}')
    print([tfidf.get_feature_names_out()[i] for i in topic.argsort()[-15:]])
    print('\n')

dtm.shape

THE TOP 15 WORDS FOR TOPIC #0
['jätte', 'saker', 'folksam', 'försäkringen', 'problem', 'hela', 'tiden', 'appen', 'fall', 'hund', 'tid', 'hunden', 'vårdguiden', 'veterinär', 'djurens']


THE TOP 15 WORDS FOR TOPIC #1
['vantar', 'processor', 'klippen', 'pensionär', 'främlingar', 'hållplatserna', 'bokstäver', 'aromer', 'personligheter', 'ringup', 'väldigt', 'ny', 'kontakt', 'anna', 'kattlådan']


THE TOP 15 WORDS FOR TOPIC #2
['dottern', 'skåp', 'nattljusolja', 'citron', 'rumsren', 'benmärg', 'rösterna', 'firman', 'ljudnivå', 'albumet', 'rätten', 'hela', 'trött', 'personerna', 'nya']


THE TOP 15 WORDS FOR TOPIC #3
['pulver', 'kräkningar', 'gånger', 'blod', 'mat', 'torrfoder', 'maten', 'majsvälling', 'vanliga', 'vatten', 'portioner', 'foder', 'diarré', 'gastro', 'magen']


THE TOP 15 WORDS FOR TOPIC #4
['återfyllnad', 'vaccinationsspruta', 'rsd', 'folie', 'postadress', 'konsultationer', 'starstruck', 'veterinär', 'moderna', 'jättebra', 'vila', 'konsultation', 'ost', 'vaccination', 'kostna

(14494, 6421)

In [ ]:
len(npr)

14494

In [ ]:
topic_results = nmf_model.transform(dtm)

topic_results.shape

(14494, 10)

In [ ]:
topic_results[5].round(2)

array([0.  , 0.26, 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ])

In [ ]:
topic_results[0].argmax()

1

In [ ]:
npr.head()

Date                                             Ärende  \
0  2022-07-05 11:02:27  hallå hallå  ja det är lite dålig täckning äve...   
1  2022-07-05 11:02:27  hallå hallå  ja det är lite dålig täckning äve...   
2  2022-07-05 11:02:27  hallå hallå  ja det är lite dålig täckning äve...   
3  2022-07-05 11:02:27  hallå hallå  ja det är lite dålig täckning äve...   
4  2022-07-05 11:02:27  hallå hallå  ja det är lite dålig täckning äve...   

                                             phrases  \
0  början ren väldigt torr, klippen  smörkniv väl...   
1  början ren väldigt torr, klippen  smörkniv väl...   
2  början ren väldigt torr, klippen  smörkniv väl...   
3  början ren väldigt torr, klippen  smörkniv väl...   
4  början ren väldigt torr, klippen  smörkniv väl...   

                                         phrase  Topic  
0                       början ren väldigt torr      1  
1   klippen  smörkniv väldigt leverpastej tryck      1  
2                               ryska kattlådan      1  
3                             ställen kattlådan      1  
4                           kattlådan sovrummet      1

In [ ]:

topic_results.argmax(axis=1)

array([1, 1, 1, ..., 0, 0, 0])

In [ ]:
npr['Topic'] = topic_results.argmax(axis=1)

In [ ]:
npr['Topic']

0        1
1        1
2        1
3        1
4        1
        ..
14489    0
14490    3
14491    0
14492    0
14493    0
Name: Topic, Length: 14494, dtype: int64

In [ ]:
npr['Topic'] = topic_results.argmax(axis=1)
npr.head(20)

Date                                             Ärende  \
0   2022-07-05 11:02:27  hallå hallå  ja det är lite dålig täckning äve...   
1   2022-07-05 11:02:27  hallå hallå  ja det är lite dålig täckning äve...   
2   2022-07-05 11:02:27  hallå hallå  ja det är lite dålig täckning äve...   
3   2022-07-05 11:02:27  hallå hallå  ja det är lite dålig täckning äve...   
4   2022-07-05 11:02:27  hallå hallå  ja det är lite dålig täckning äve...   
5   2022-07-05 11:02:27  hallå hallå  ja det är lite dålig täckning äve...   
6   2022-07-05 11:02:27  hallå hallå  ja det är lite dålig täckning äve...   
7   2022-07-05 11:02:27  hallå hallå  ja det är lite dålig täckning äve...   
8   2022-07-05 11:02:27  hallå hallå  ja det är lite dålig täckning äve...   
9   2022-07-05 11:02:27  hallå hallå  ja det är lite dålig täckning äve...   
10  2022-07-05 11:02:27  hallå hallå  ja det är lite dålig täckning äve...   
11  2022-07-05 11:02:27  hallå hallå  ja det är lite dålig täckning äve...   
12  2022-07-05 11:02:27  hallå hallå  ja det är lite dålig täckning äve...   
13  2022-07-05 11:02:27  hallå hallå  ja det är lite dålig täckning äve...   
14  2022-07-05 11:02:27  hallå hallå  ja det är lite dålig täckning äve...   
15  2022-07-05 11:02:27  hallå hallå  ja det är lite dålig täckning äve...   
16  2022-07-05 11:02:27  hallå hallå  ja det är lite dålig täckning äve...   
17  2022-07-05 11:02:27  hallå hallå  ja det är lite dålig täckning äve...   
18  2022-07-05 11:02:27  hallå hallå  ja det är lite dålig täckning äve...   
19  2022-07-05 11:02:27  hallå hallå  ja det är lite dålig täckning äve...   

                                              phrases  \
0   början ren väldigt torr, klippen  smörkniv väl...   
1   början ren väldigt torr, klippen  smörkniv väl...   
2   början ren väldigt torr, klippen  smörkniv väl...   
3   början ren väldigt torr, klippen  smörkniv väl...   
4   början ren väldigt torr, klippen  smörkniv väl...   
5   början ren väldigt torr, klippen  smörkniv väl...   
6   början ren väldigt torr, klippen  smörkniv väl...   
7   början ren väldigt torr, klippen  smörkniv väl...   
8   början ren väldigt torr, klippen  smörkniv väl...   
9   början ren väldigt torr, klippen  smörkniv väl...   
10  början ren väldigt torr, klippen  smörkniv väl...   
11  början ren väldigt torr, klippen  smörkniv väl...   
12  början ren väldigt torr, klippen  smörkniv väl...   
13  början ren väldigt torr, klippen  smörkniv väl...   
14  början ren väldigt torr, klippen  smörkniv väl...   
15  början ren väldigt torr, klippen  smörkniv väl...   
16  början ren väldigt torr, klippen  smörkniv väl...   
17  början ren väldigt torr, klippen  smörkniv väl...   
18  början ren väldigt torr, klippen  smörkniv väl...   
19  början ren väldigt torr, klippen  smörkniv väl...   

                                          phrase  Topic  
0                        början ren väldigt torr      1  
1    klippen  smörkniv väldigt leverpastej tryck      1  
2                                ryska kattlådan      1  
3                              ställen kattlådan      1  
4                            kattlådan sovrummet      1  
5                                        allting      1  
6                                      ny rummet      1  
7                                        tålamod      1  
8                                 typ hela tiden      1  
9                                   extra vatten      1  
10                                  fall nyfiken      1  
11                                         köket      1  
12                                 johanna kväll      1  
13                                    fel ställe      1  
14                            jättebra messalian      1  
15                                       problem      1  
16                                       grottan      1  
17                                 bokstäver typ      1  
18                                          sätt      1  
19                    

In [ ]:
npr.tail(10)

Date                                             Ärende  \
14484  2022-07-05 11:02:27  välkommen till djurens vårdguiden pratar med e...   
14485  2022-07-05 11:02:27  vårdguiden prata med elin hejsan mitt namn är ...   
14486  2022-07-05 11:02:27  kommer inte 2288 djurens vårdguiden prata med ...   
14487  2022-07-05 11:02:27  välkommen till 28 djurens vårdguiden prata med...   
14488  2022-07-05 11:02:27  välkommen till 2288 djurens vårdguiden prata m...   
14489  2022-07-05 11:02:27  kommer det 2288 djurens vårdguiden pratar man ...   
14490  2022-07-05 11:02:27  välkommen till 2288 djurens vårdguiden prata m...   
14491  2022-07-05 11:02:27  välkommen till djurens vårdguiden prata med el...   
14492  2022-07-05 11:02:27  välkommen till 2288 djurens vårdguiden pratar ...   
14493  2022-07-05 11:02:27  välkommen till 2288 djurens vårdguiden prata m...   

                                                 phrases               phrase  \
14484  slickar, hela tiden, riktigt otur, problem, ov...   djurens vårdguiden   
14485  hundar, katter, djurens vårdguiden, vaccinet, ...   djurens vårdguiden   
14486  helgen, applåd applåd applåd, hallsberg väldig...   djurens vårdguiden   
14487  hund, djurens vårdguiden, gunilla, appen, firs...   djurens vårdguiden   
14488  tid, djurens vårdguiden, katter, djur hundar, ...   djurens vårdguiden   
14489  samtalet, hunden, kompisar, aktuell vikt, rece...   djurens vårdguiden   
14490  jättebra vatten, vuxen mat, blöt mat, blod, ex...   djurens vårdguiden   
14491  valpen, konsultation, akut djursjukhus, kontak...   djurens vårdguiden   
14492  vanligt tecken, padda, veterinär, munnen, appe...   djurens vårdguiden   
14493  veckor, hund nos, vaccinet, håll koll, andning...   djurens vårdguiden   

       Topic  
14484      0  
14485      0  
14486      0  
14487      0  
14488      0  
14489      0  
14490      3  
14491      0  
14492      0  
14493      0

In [ ]:
##npr['Topic'] = topic_results.argmax(axis=1)



#topicdict  = {0:'health',1:'election',2:'legis',3:'policy',4:'candidates',5:'music',6:'educaion'}

#npr['Topic Label'] = npr['Topic'].map(topicdict)

#npr.head(10)